### resource not found
GET http://localhost:3000/api/null

### Récupération des tous les auteurs
GET http://localhost:3000/api/authors

### Récupération de tous les éditeurs
GET http://localhost:3000/api/publishers

### Récupération des tous les genres
GET http://localhost:3000/api/genre

### Récupération des livres
GET http://localhost:3000/api/book

### Récupération d'un auteur
GET http://localhost:3000/api/authors/2

### Récupération d'un editeur
GET http://localhost:3000/api/publisher/1

### Récupération d'un genre
GET http://localhost:3000/api/genre/1

### Récupération d'un livre
GET http://localhost:3000/api/book/7

### Ajout d'auteur
POST http://localhost:3000/api/authors
Content-Type: application/json

{
    "firstname": "Victor",
    "lastname": "Hugo",
    "country_iso_2": "fr",
    "birthdate": "1885-05-22"
}

### Ajout d'un éditeur
POST http://localhost:3000/api/publishers
Content-Type: application/json

{
    "name": "Livre de Poche",
    "country_iso_2": "fr"
}

### Ajout d'un genre
POST http://localhost:3000/api/genre
Content-Type: application/json

{
    "label": "Science-fiction"
}

### Ajout d'un livre
POST http://localhost:3000/api/book
Content-Type: application/json

{
    "reference": "5593",
    "title": "Trone de fer : Feus et sang",
    "locale": "us_US",
    "year": 2018,
    "page_count": 800,
    "chapter_count": 35,
    "front_cover": "NA",
    "publisher_id": 1,
    "genre_id" : [1],
    "author_id": [1]
}

### Update d'auteur
PATCH http://localhost:3000/api/authors/2
Content-Type: application/json

{
    "country_iso_2": "us"
}

### Update d'un éditeur
PATCH http://localhost:3000/api/publisher/2
Content-Type: application/json

{
    "country_iso_2": "us"
}

### Update d'un genre
PATCH http://localhost:3000/api/genre/2
Content-Type: application/json

{
    "label": "Fantastique"
}


### Update d'un livre
PATCH http://localhost:3000/api/book/2
Content-Type: application/json

{
    "locale": "fr-FR"
}
### delete d'auteur
DELETE http://localhost:3000/api/authors/2

### delete d'auteur
DELETE http://localhost:3000/api/publisher/3

### delete d'un genre
DELETE http://localhost:3000/api/genre/9


### delete d'un livre
DELETE http://localhost:3000/api/book/8